# Generated by Django 2.0 on 2019-03-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('executor_type', models.CharField(choices=[('DATABRICKS', 'DATABRICKS'), ('ATHENA', 'ATHENA')], max_length=256)),
                ('create_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_item_as_creator', to=settings.AUTH_USER_MODEL)),
                ('maintainer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_item_as_maintainer', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_item_as_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
