# Generated by Django 2.0 on 2019-03-13 16:05

import catalogue.models
from django.db import migrations, models
import django.db.models.deletion
import lily.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('sample', lily.base.models.JSONSchemaField(blank=True, default=[])),
                ('spec', lily.base.models.JSONSchemaField(validators=[catalogue.models.spec_validator])),
                ('executor_type', models.CharField(choices=[('DATABRICKS', 'DATABRICKS'), ('ATHENA', 'ATHENA')], max_length=256)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_item_as_creator', to='account.Account')),
                ('maintained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_item_as_maintainer', to='account.Account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_item_as_updater', to='account.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
