# Generated by Django 2.1.10 on 2019-08-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20190501_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='data_path',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
