# Generated by Django 2.1.15 on 2020-04-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190501_1030'),
        ('catalogue', '0003_auto_20190501_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='researchers',
            field=models.ManyToManyField(to='account.Account'),
        ),
    ]
