# Generated by Django 2.1.15 on 2020-04-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_catalogueitem_researchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
