# Generated by Django 2.1.10 on 2019-08-27 12:17

from django.db import migrations
import lily.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20190822_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='executor_type',
            field=lily.base.models.EnumChoiceField(
                choices=[
                    ('DATABRICKS', 'DATABRICKS'),
                    ('ATHENA', 'ATHENA'),
                    ('LOCAL', 'LOCAL')
                ],
                enum_name='Executor',
                max_length=256),
        ),
    ]
