
#
# Account Types
#
ACCOUNT_TYPE_RESEARCHER = 'RESEARCHER'

ACCOUNT_TYPE_ADMIN = 'ADMIN'

ACCOUNT_TYPE_ANONYMOUS = 'ANONYMOUS'

ACCOUNT_TYPE_ANY = [
    ACCOUNT_TYPE_RESEARCHER,
    ACCOUNT_TYPE_ADMIN,
]

ACCOUNT_TYPE_ANY_WITH_ANONYMOUS = [ACCOUNT_TYPE_ANONYMOUS, *ACCOUNT_TYPE_ANY]
