#!/bin/bash

export GOOGLE_OAUTH2_CLIENT_ID=961918528927-12heq0l9f1tep1igb29tatkf2pr2p5f7.apps.googleusercontent.com

export GOOGLE_OAUTH2_CLIENT_SECRET=r0-vjb8dz6LcfSyAUlghuQEP

#
# AUTH
#
export AUTH_TOKEN_SECRET_KEY='74MT6rVgcazK6dXruBpRq'

export AUTH_TOKEN_EXPIRATION_SECONDS=86400

export AUTH_REQUEST_EXPIRATION_SECONDS=600

#
# NGROK PROXY
#
export NGROK_AUTH_TOKEN=56YEhE58pVGEtn9Ymf7Wo_74MT6rVgcazK6dXruBpRq

#
# DB
#
export POSTGRES_DB=lakey_service

export POSTGRES_USER=local

export POSTGRES_PASSWORD=''

export POSTGRES_HOST=localhost

export POSTGRES_PORT=5434
