# Generated by Django 2.1.7 on 2019-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='normalized_spec',
            field=models.TextField(blank=True, default=''),
        ),
    ]
