# Generated by Django 2.1.15 on 2020-04-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_downloadrequest_normalized_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrequest',
            name='uri',
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='blob_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
