# Generated by Django 2.1.10 on 2019-08-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunk', '0003_auto_20190823_0938'),
        ('downloader', '0002_downloadrequest_normalized_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='chunks',
            field=models.ManyToManyField(to='chunk.Chunk'),
        ),
    ]
