# Generated by Django 2.1.10 on 2019-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_downloadrequest_chunks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='chunks',
            field=models.ManyToManyField(to='chunk.Chunk'),
        ),
    ]
