# Generated by Django 2.1.7 on 2019-05-01 10:30

from django.db import migrations
import lily.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=lily.base.models.EnumChoiceField(
                choices=[
                    ('RESEARCHER', 'RESEARCHER'),
                    ('ADMIN', 'ADMIN'),
                ],
                default='RESEARCHER',
                enum_name='account_type',
                max_length=64),
        ),
    ]
