# Generated by Django 2.1.15 on 2020-04-19 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lily.base.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20190501_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=lily.base.models.EnumChoiceField(
                choices=[
                    ('RESEARCHER', 'RESEARCHER'),
                    ('ADMIN', 'ADMIN')
                ],
                enum_name='AccountType',
                max_length=16),
        ),
    ]
