# Generated by Django 2.1.7 on 2019-07-19 09:37

from django.db import migrations, models
import django.db.models.deletion
import lily.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0003_auto_20190501_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'),
                ),
                (
                    'borders',
                    lily.base.models.JSONSchemaField(),
                ),
                (
                    'catalogue_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chunks',
                        to='catalogue.CatalogueItem'),
                ),
            ],
        ),
    ]
