# Generated by Django 2.1.7 on 2019-07-29 09:54

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('chunk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='count',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='chunk',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chunk',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
