# Generated by Django 2.1.10 on 2019-08-19 11:34

import chunk.models
from django.db import migrations, models
import lily.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('chunk', '0002_auto_20190729_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='requested_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chunk',
            name='borders',
            field=lily.base.models.JSONSchemaField(validators=[chunk.models.distribution_validator]),
        ),
    ]
