# Generated by Django 2.1.10 on 2019-08-09 05:38

import chunk.models
from django.db import migrations
import lily.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('chunk', '0002_auto_20190729_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='borders',
            field=lily.base.models.JSONSchemaField(
                validators=[chunk.models.distribution_validator]
            ),
        ),
    ]
