# Generated by Django 2.1.10 on 2019-08-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunk', '0003_auto_20190819_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='requested_count',
            field=models.IntegerField(default=0),
        ),
    ]
