# Generated by Django 2.1.10 on 2019-08-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunk', '0003_auto_20190809_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='count',
        ),
    ]
