# Generated by Django 2.1.10 on 2019-08-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunk', '0004_auto_20190819_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='requested_count',
        ),
    ]
