# Generated by Django 2.1.10 on 2019-08-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunk', '0005_chunk_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='data_path',
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                unique=True),
        ),
    ]
