# Generated by Django 2.1.10 on 2019-08-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_downloadrequest_normalized_spec'),
        ('chunk', '0005_remove_chunk_requested_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='download_request',
            field=models.ManyToManyField(to='downloader.DownloadRequest'),
        ),
    ]
